// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication38.Models;

namespace WebApplication38.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication38.Models.AirlineDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("airlineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enddatetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("flightNumber")
                        .HasColumnType("int");

                    b.Property<string>("fromPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instrumentUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("meal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberofRows")
                        .HasColumnType("int");

                    b.Property<string>("scheduleddays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("startdatetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("tNoBusinessClassSeats")
                        .HasColumnType("int");

                    b.Property<int>("tNoNonBusinessClassSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("ticketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("toPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uploadLogo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AirlineDetails");
                });

            modelBuilder.Entity("WebApplication38.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
